//
// BrandedFoodObjectDietLabelsVegan.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information on this item&#x27;s compatibility with the Vegan diets */
open class BrandedFoodObjectDietLabelsVegan: JSONEncodable {
    /** Diet name */
    public var name: String?
    /** Boolean describing if this item is compatible with this diet */
    public var isCompatible: Bool?
    /** Numeric representation of how compatible this item is with this diet. Higher values indicate more compatibility */
    public var compatibilityLevel: Int32?
    /** Boolean that indicates if we are confident in how this item is graded for this diet */
    public var confidence: Int32?
    /** Description of our confidence that this item was graded correctly */
    public var confidenceDescription: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["is_compatible"] = self.isCompatible
        nillableDictionary["compatibility_level"] = self.compatibilityLevel?.encodeToJSON()
        nillableDictionary["confidence"] = self.confidence?.encodeToJSON()
        nillableDictionary["confidence_description"] = self.confidenceDescription

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
