//
// BrandedFoodObjectPackagingPhotosNutrition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing photos of this item&#x27;s nutrition label */
open class BrandedFoodObjectPackagingPhotosNutrition: JSONEncodable {
    /** Small photo of this item&#x27;s nutrition label */
    public var small: String?
    /** Thumbnail photo of this item&#x27;s nutrition label */
    public var thumb: String?
    /** Full-sized photo of this item&#x27;s nutrition label */
    public var display: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["small"] = self.small
        nillableDictionary["thumb"] = self.thumb
        nillableDictionary["display"] = self.display

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
