//
// BrandedFoodObjectPortions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information on a specific food portion found in this item */
open class BrandedFoodObjectPortions: JSONEncodable {
    /** The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp) */
    public var measurementUnit: String?
    /** Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza. */
    public var description: String?
    /** Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced) */
    public var modifier: String?
    /** The weight of the measure in grams */
    public var gramWeight: BigDecimal?
    /** The number of observations on which the measure is based */
    public var dataPoints: Int32?
    /** Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value. */
    public var footnote: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["measurement_unit"] = self.measurementUnit
        nillableDictionary["description"] = self.description
        nillableDictionary["modifier"] = self.modifier
        nillableDictionary["gram_weight"] = self.gramWeight?.encodeToJSON()
        nillableDictionary["data_points"] = self.dataPoints?.encodeToJSON()
        nillableDictionary["footnote"] = self.footnote

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
