//
// BrandedFoodObjectServingUsda.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Serving information from the USDA */
open class BrandedFoodObjectServingUsda: JSONEncodable {
    /** Serving size */
    public var size: String?
    /** Measurement unit for each serving (e.g. if measure is 3 tsp, the unit is tsp) */
    public var measurementUnit: String?
    /** Serving size description */
    public var sizeFulltext: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["size"] = self.size
        nillableDictionary["measurement_unit"] = self.measurementUnit
        nillableDictionary["size_fulltext"] = self.sizeFulltext

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
