//
// BrandedFoodObjectPackagingPhotos.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A object containing a collection of photos of this item&#x27;s packaging */
open class BrandedFoodObjectPackagingPhotos: JSONEncodable {
    public var front: BrandedFoodObjectPackagingPhotosFront?
    public var nutrition: BrandedFoodObjectPackagingPhotosNutrition?
    public var ingredients: BrandedFoodObjectPackagingPhotosIngredients?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["front"] = self.front?.encodeToJSON()
        nillableDictionary["nutrition"] = self.nutrition?.encodeToJSON()
        nillableDictionary["ingredients"] = self.ingredients?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
