//
// BrandedFoodObjectServing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing serving information for this item */
open class BrandedFoodObjectServing: JSONEncodable {
    public var chomp: BrandedFoodObjectServingChomp?
    public var usda: BrandedFoodObjectServingUsda?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["chomp"] = self.chomp?.encodeToJSON()
        nillableDictionary["usda"] = self.usda?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
