//
// BrandedFoodObjectPackagingPhotosIngredients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing photos of the ingredients on this item&#x27;s packaging */
open class BrandedFoodObjectPackagingPhotosIngredients: JSONEncodable {
    /** Small photo of the ingredients on this item&#x27;s packaging */
    public var small: String?
    /** Thumbnail photo of the ingredients on this item&#x27;s packaging */
    public var thumb: String?
    /** Full-sized photo of the ingredients on this item&#x27;s packaging */
    public var display: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["small"] = self.small
        nillableDictionary["thumb"] = self.thumb
        nillableDictionary["display"] = self.display

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
