//
// BrandedFoodObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information for a specific nutrient found in this food item */
open class BrandedFoodObjectNutrients: JSONEncodable {
    /** Nutrient name */
    public var name: String?
    /** Amount of the nutrient per 100g of food */
    public var per100g: BigDecimal?
    /** The unit used for the measure of this nutrient */
    public var measurementUnit: String?
    /** Nutrient rank */
    public var rank: Int32?
    /** Number of observations on which the value is based */
    public var dataPoints: Int32?
    /** Description of the nutrient source */
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["per_100g"] = self.per100g?.encodeToJSON()
        nillableDictionary["measurement_unit"] = self.measurementUnit
        nillableDictionary["rank"] = self.rank?.encodeToJSON()
        nillableDictionary["data_points"] = self.dataPoints?.encodeToJSON()
        nillableDictionary["description"] = self.description

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
