//
// BrandedFoodObjectNutrientsChomp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class BrandedFoodObjectNutrientsChomp: JSONEncodable {
    /** Nutrient name */
    public var name: String?
    /** The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp) */
    public var measurementUnit: String?
    /** Amount of the nutrient per 100g of food */
    public var per100g: BigDecimal?
    /** Nutrient value per serving */
    public var perServing: BigDecimal?
    /** Total nutrient value */
    public var total: BigDecimal?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["measurement_unit"] = self.measurementUnit
        nillableDictionary["per_100g"] = self.per100g?.encodeToJSON()
        nillableDictionary["per_serving"] = self.perServing?.encodeToJSON()
        nillableDictionary["total"] = self.total?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
