//
// BrandedFoodObjectIngredients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing this item&#x27;s ingredients in order of highest value to least */
open class BrandedFoodObjectIngredients: JSONEncodable {
    /** This item&#x27;s ingredients as seen on ChompThis.com */
    public var chomp: String?
    /** This branded food item&#x27;s ingredients according to the USDA */
    public var usda: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["chomp"] = self.chomp
        nillableDictionary["usda"] = self.usda

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
