//
// BrandedFoodObjectServingChomp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Serving information from as seen on ChompThis.com */
open class BrandedFoodObjectServingChomp: JSONEncodable {
    /** Serving size with measurement unit (e.g. if measure is 3 tsp, the unit is tsp) */
    public var size: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["size"] = self.size

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
