//
// IngredientObjectCalorieConversionFactor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing the multiplication factors to be used when calculating energy from macronutrients for a specific food. */
open class IngredientObjectCalorieConversionFactor: JSONEncodable {
    /** The multiplication factor for protein */
    public var proteinValue: BigDecimal?
    /** The multiplication factor for fat */
    public var fatValue: BigDecimal?
    /** The multiplication factor for carbohydrates */
    public var carbohydrateValue: BigDecimal?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["protein_value"] = self.proteinValue?.encodeToJSON()
        nillableDictionary["fat_value"] = self.fatValue?.encodeToJSON()
        nillableDictionary["carbohydrate_value"] = self.carbohydrateValue?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
