//
// IngredientObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing nutrient information from each source */
open class IngredientObjectNutrients: JSONEncodable {
    /** An array containing an object for each nutrient data point as found in the USDA database */
    public var usda: [BrandedFoodObjectNutrientsUsda]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["usda"] = self.usda?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
