//
// RecipeObjectNutrientsCalories.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RecipeObjectNutrientsCalories: JSONEncodable {
    /** Nutrient name */
    public var title: String?
    /** The amount of this nutrient in this recipe */
    public var value: String?
    /** The daily recommended percent total for this nutrient */
    public var percent: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["value"] = self.value
        nillableDictionary["percent"] = self.percent

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
