//
// RecipeObjectMetaImages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing this recipe&#x27;s image URLs */
open class RecipeObjectMetaImages: JSONEncodable {
    /** Extra large recipe image */
    public var extraLarge: String?
    /** Large recipe image */
    public var large: String?
    /** Standard recipe image */
    public var standard: String?
    /** Grid view recipe image */
    public var gridView: String?
    /** Small recipe image */
    public var small: String?
    /** Thumbnail recipe image */
    public var thumbnail: String?
    /** Extra small recipe image */
    public var extraSmall: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["extra_large"] = self.extraLarge
        nillableDictionary["large"] = self.large
        nillableDictionary["standard"] = self.standard
        nillableDictionary["grid_view"] = self.gridView
        nillableDictionary["small"] = self.small
        nillableDictionary["thumbnail"] = self.thumbnail
        nillableDictionary["extra_small"] = self.extraSmall

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
