//
// RecipeObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing nutrient information for this recipe */
open class RecipeObjectNutrients: JSONEncodable {
    /** An array containing information for calories found in this recipe */
    public var calories: [RecipeObjectNutrientsCalories]?
    /** An array containing information for this recipe&#x27;s daily recommended value of certain nutrients */
    public var dailyValues: [RecipeObjectNutrientsCalories]?
    /** An array containing information for fat found in this recipe */
    public var fat: [RecipeObjectNutrientsCalories]?
    /** An array containing information for carbs found in this recipe */
    public var carbs: [RecipeObjectNutrientsCalories]?
    /** An array containing information for vitamins found in this recipe */
    public var vitamins: [RecipeObjectNutrientsCalories]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["calories"] = self.calories?.encodeToJSON()
        nillableDictionary["daily_values"] = self.dailyValues?.encodeToJSON()
        nillableDictionary["fat"] = self.fat?.encodeToJSON()
        nillableDictionary["carbs"] = self.carbs?.encodeToJSON()
        nillableDictionary["vitamins"] = self.vitamins?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
