//
// RecipeObjectItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information for this specific item. */
open class RecipeObjectItems: JSONEncodable {
    /** Unique recipe ID */
    public var id: String?
    /** Recipe title */
    public var title: String?
    public var meta: RecipeObjectMeta?
    public var categories: [String]?
    /** The author of this recipe. You must attribute this author when displaying this recipe. */
    public var author: String?
    public var keywords: [String]?
    public var topics: [String]?
    public var attributes: RecipeObjectAttributes?
    /** An array containing this recipe&#x27;s ingredients */
    public var ingredients: [RecipeObjectIngredients]?
    public var baseIngredients: [String]?
    public var nutrients: RecipeObjectNutrients?
    public var diabeticExchanges: [String]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["title"] = self.title
        nillableDictionary["meta"] = self.meta?.encodeToJSON()
        nillableDictionary["categories"] = self.categories?.encodeToJSON()
        nillableDictionary["author"] = self.author
        nillableDictionary["keywords"] = self.keywords?.encodeToJSON()
        nillableDictionary["topics"] = self.topics?.encodeToJSON()
        nillableDictionary["attributes"] = self.attributes?.encodeToJSON()
        nillableDictionary["ingredients"] = self.ingredients?.encodeToJSON()
        nillableDictionary["base_ingredients"] = self.baseIngredients?.encodeToJSON()
        nillableDictionary["nutrients"] = self.nutrients?.encodeToJSON()
        nillableDictionary["diabetic_exchanges"] = self.diabeticExchanges?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
