//
// RecipeObjectIngredients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information about a specific recipe ingredient */
open class RecipeObjectIngredients: JSONEncodable {
    /** The quantity of this ingredient */
    public var quantity: String?
    /** A description of this ingredient */
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["quantity"] = self.quantity
        nillableDictionary["description"] = self.description

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
