//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI: APIBase {
    /**
     Get a branded food item using a barcode
     - parameter code: (query) UPC/EAN barcode  __Example:__ &amp;code&#x3D;0842234000988  __Tips:__    - Use our [food lookup tool](https://chompthis.com/api/lookup.php).   - Read [this article](https://desk.zoho.com/portal/chompthis/kb/articles/im-having-trouble-getting-matches-for-barcodes-what-can-id-do) for general tips and tricks.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func foodBrandedBarcodePhpGet(code: String, completion: @escaping ((_ data: BrandedFoodObject?, _ error: ErrorResponse?) -> Void)) {
        foodBrandedBarcodePhpGetWithRequestBuilder(code: code).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a branded food item using a barcode
     - GET /food/branded/barcode.php
     - # Get data for a branded food using the food's UPC/EAN barcode.  __Example:__ ```https://chompthis.com/api/v2/food/branded/barcode.php?api_key=API_KEY&code=CODE``` 
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "items" : [ {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  }, {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  } ]
}}]
     - parameter code: (query) UPC/EAN barcode  __Example:__ &amp;code&#x3D;0842234000988  __Tips:__    - Use our [food lookup tool](https://chompthis.com/api/lookup.php).   - Read [this article](https://desk.zoho.com/portal/chompthis/kb/articles/im-having-trouble-getting-matches-for-barcodes-what-can-id-do) for general tips and tricks.  
     - returns: RequestBuilder<BrandedFoodObject> 
     */
    open class func foodBrandedBarcodePhpGetWithRequestBuilder(code: String) -> RequestBuilder<BrandedFoodObject> {
        let path = "/food/branded/barcode.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
                        "code": code
        ])

        let requestBuilder: RequestBuilder<BrandedFoodObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter source
     */
    public enum Source_foodBrandedIdPhpGet: String { 
        case chomp = "Chomp"
        case usda = "USDA"
    }

    /**
     Get a branded food item using an ID number
     - parameter id: (query) The ID number of a branded food item.  __Example #1:__ &amp;id&#x3D;15  __Example #2:__ &amp;id&#x3D;FDC_ID&amp;source&#x3D;USDA  ___Tip:__ Get started by using our  [ood lookup tool](https://chompthis.com/api/lookup.php)._  
     - parameter source: (query) Configure the endpoint to accept food IDs from various data sources. This endpoint defaults to Chomp but can accept FDC IDs.  __Example:__ &amp;source&#x3D;Chomp  ___Important Note:__ Pass in &amp;source&#x3D;USDA if you want to look up food items using a USDA FDC ID._  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func foodBrandedIdPhpGet(id: Int32, source: Source_foodBrandedIdPhpGet? = nil, completion: @escaping ((_ data: BrandedFoodObject?, _ error: ErrorResponse?) -> Void)) {
        foodBrandedIdPhpGetWithRequestBuilder(id: id, source: source).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a branded food item using an ID number
     - GET /food/branded/id.php
     - # Get data for a branded food using Chomp's internal ID number.  _Alternatively, set the \"source\" parameter to \"USDA\" and use the food's FDC ID._  __Example:__ ```https://chompthis.com/api/v2/food/branded/id.php?api_key=API_KEY&id=ID``` 
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "items" : [ {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  }, {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  } ]
}}]
     - parameter id: (query) The ID number of a branded food item.  __Example #1:__ &amp;id&#x3D;15  __Example #2:__ &amp;id&#x3D;FDC_ID&amp;source&#x3D;USDA  ___Tip:__ Get started by using our  [ood lookup tool](https://chompthis.com/api/lookup.php)._  
     - parameter source: (query) Configure the endpoint to accept food IDs from various data sources. This endpoint defaults to Chomp but can accept FDC IDs.  __Example:__ &amp;source&#x3D;Chomp  ___Important Note:__ Pass in &amp;source&#x3D;USDA if you want to look up food items using a USDA FDC ID._  (optional)
     - returns: RequestBuilder<BrandedFoodObject> 
     */
    open class func foodBrandedIdPhpGetWithRequestBuilder(id: Int32, source: Source_foodBrandedIdPhpGet? = nil) -> RequestBuilder<BrandedFoodObject> {
        let path = "/food/branded/id.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
                        "id": id.encodeToJSON(),
                        "source": source?.rawValue
        ])

        let requestBuilder: RequestBuilder<BrandedFoodObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter limit
     */
    public enum Limit_foodBrandedNamePhpGet: Int32 { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
        case _5 = 5
        case _6 = 6
        case _7 = 7
        case _8 = 8
        case _9 = 9
        case _10 = 10
    }

    /**
     Get a branded food item by name
     - parameter name: (query) Search for branded food items using a general food name keyword. This does not have to exactly match the \&quot;official\&quot; name for the food.  __Example:__ &amp;name&#x3D;Starburst  ___Tip:__ Get started by using our [food lookup tool](https://chompthis.com/api/lookup.php)._  
     - parameter limit: (query) Set maximum number of records you want the API to return.  __Example:__ &amp;limit&#x3D;10  (optional)
     - parameter page: (query) This is how you paginate the search result. By default, you will see the first 10 records. You must increment the page number to access the next 10 records, and so on.  __Example__: &amp;page&#x3D;1  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func foodBrandedNamePhpGet(name: String, limit: Limit_foodBrandedNamePhpGet? = nil, page: Int32? = nil, completion: @escaping ((_ data: BrandedFoodObject?, _ error: ErrorResponse?) -> Void)) {
        foodBrandedNamePhpGetWithRequestBuilder(name: name, limit: limit, page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a branded food item by name
     - GET /food/branded/name.php
     - # Search for branded food items by name.  This API endpoint is only available to Standard and Premium API subscribers. Please consider upgrading your subscription if you are subscribed to the Limited plan. _[Read this](https://desk.zoho.com/portal/chompthis/kb/articles/can-i-upgrade-downgrade-my-subscription) if you aren't sure how to upgrade your subscription._  __Example:__ ```https://chompthis.com/api/v2/food/branded/name.php?api_key=API_KEY&name=NAME``` 
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "items" : [ {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  }, {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  } ]
}}]
     - parameter name: (query) Search for branded food items using a general food name keyword. This does not have to exactly match the \&quot;official\&quot; name for the food.  __Example:__ &amp;name&#x3D;Starburst  ___Tip:__ Get started by using our [food lookup tool](https://chompthis.com/api/lookup.php)._  
     - parameter limit: (query) Set maximum number of records you want the API to return.  __Example:__ &amp;limit&#x3D;10  (optional)
     - parameter page: (query) This is how you paginate the search result. By default, you will see the first 10 records. You must increment the page number to access the next 10 records, and so on.  __Example__: &amp;page&#x3D;1  (optional)
     - returns: RequestBuilder<BrandedFoodObject> 
     */
    open class func foodBrandedNamePhpGetWithRequestBuilder(name: String, limit: Limit_foodBrandedNamePhpGet? = nil, page: Int32? = nil) -> RequestBuilder<BrandedFoodObject> {
        let path = "/food/branded/name.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
                        "name": name,
                        "limit": limit?.rawValue,
                        "page": page?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<BrandedFoodObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter diet
     */
    public enum Diet_foodBrandedSearchPhpGet: String { 
        case vegan = "Vegan"
        case vegetarian = "Vegetarian"
        case glutenFree = "Gluten Free"
    }

    /**
     * enum for parameter limit
     */
    public enum Limit_foodBrandedSearchPhpGet: Int32 { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
        case _5 = 5
        case _6 = 6
        case _7 = 7
        case _8 = 8
        case _9 = 9
        case _10 = 10
    }

    /**
     Get data for branded food items using various search parameters
     - parameter allergen: (query) Filter the search to only include branded foods that contain a specific allergen.  __Example__: &amp;allergen&#x3D;Peanuts  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter brand: (query) Filter the search to only include branded foods that are owned by a specific brand.  __Example__: &amp;brand&#x3D;Starbucks  (optional)
     - parameter category: (query) Filter the search to only include branded foods from a specific category.  __Example__: &amp;category&#x3D;Plant Based Foods  (optional)
     - parameter country: (query) Filter the search to only include branded foods that are sold in a specific country.  __Example__: &amp;country&#x3D;United States  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter diet: (query) Filter the search to only include branded foods that are considered compatible with a specific diet.  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter ingredient: (query) Filter the search to only include branded foods that contain a specific ingredient.  __Example__: &amp;ingredient&#x3D;Salt  (optional)
     - parameter keyword: (query) Filter the search to only include branded foods that are associated with a specific keyword.  __Example__: &amp;keyword&#x3D;Organic  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter mineral: (query) Filter the search to only include branded foods that contain a specific mineral.  __Example__: &amp;mineral&#x3D;Potassium  (optional)
     - parameter nutrient: (query) Filter the search to only include branded foods that contain a specific nutrient.  __Example__: &amp;nutrient&#x3D;Caffeine  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter palmOil: (query) Filter the search to only include branded foods that contain a specific ingredient made using palm oil.  __Example__: &amp;palm_oil&#x3D;E160a Beta Carotene  (optional)
     - parameter trace: (query) Filter the search to only include branded foods that contain a specific trace ingredient.  __Example__: &amp;trace&#x3D;Tree Nuts  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter vitamin: (query) Filter the search to only include branded foods that contain a specific vitamin.  __Example__: &amp;vitamin&#x3D;Biotin  (optional)
     - parameter limit: (query) Set maximum number of records you want the API to return.  __Example:__ &amp;limit&#x3D;10  (optional)
     - parameter page: (query) This is how you paginate the search result. By default, you will see the first 10 records. You must increment the page number to access the next 10 records, and so on.  __Example__: &amp;page&#x3D;1  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func foodBrandedSearchPhpGet(allergen: String? = nil, brand: String? = nil, category: String? = nil, country: String? = nil, diet: Diet_foodBrandedSearchPhpGet? = nil, ingredient: String? = nil, keyword: String? = nil, mineral: String? = nil, nutrient: String? = nil, palmOil: String? = nil, trace: String? = nil, vitamin: String? = nil, limit: Limit_foodBrandedSearchPhpGet? = nil, page: Int32? = nil, completion: @escaping ((_ data: BrandedFoodObject?, _ error: ErrorResponse?) -> Void)) {
        foodBrandedSearchPhpGetWithRequestBuilder(allergen: allergen, brand: brand, category: category, country: country, diet: diet, ingredient: ingredient, keyword: keyword, mineral: mineral, nutrient: nutrient, palmOil: palmOil, trace: trace, vitamin: vitamin, limit: limit, page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get data for branded food items using various search parameters
     - GET /food/branded/search.php
     - # Search for branded food items using various parameters.  This API endpoint is only available to Standard and Premium API subscribers. Please consider upgrading your subscription if you are subscribed to the Limited plan. _[Read this](https://desk.zoho.com/portal/chompthis/kb/articles/can-i-upgrade-downgrade-my-subscription) if you aren't sure how to upgrade your subscription._  __Example:__ ```https://chompthis.com/api/v2/food/branded/search.php?api_key=API_KEY&brand=BRAND&country=COUNTRY&page=1```  ___Tip:__ Get started by using the [Query Builder](https://chompthis.com/api/build.php)._ 
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "items" : [ {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  }, {
    "minerals" : [ "minerals", "minerals" ],
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "keywords" : [ "keywords", "keywords" ],
    "country_details" : {
      "english_speaking" : 6,
      "non_english_speaking" : 6
    },
    "description" : "description",
    "has_english_ingredients" : true,
    "palm_oil_ingredients" : [ "palm_oil_ingredients", "palm_oil_ingredients" ],
    "serving" : {
      "total" : 5,
      "size_fulltext" : "size_fulltext",
      "size" : 1,
      "measurement_unit" : "measurement_unit"
    },
    "nutrients" : {
      "chomp" : [ {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      }, {
        "total" : 7.061401241503109,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "per_100g" : 5.637376656633329,
        "per_serving" : 2.3021358869347655
      } ],
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "protein_conversion_factor" : 1.1730742509559433,
    "packaging_photos" : {
      "nutrition" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "ingredients" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      },
      "front" : {
        "small" : "small",
        "thumb" : "thumb",
        "display" : "display"
      }
    },
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "ingredients" : "ingredients",
    "categories" : [ "categories", "categories" ],
    "common_name" : "common_name",
    "barcode" : "barcode",
    "brand" : "brand",
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ],
    "package" : {
      "quantity" : 0,
      "size" : 6
    },
    "traces" : [ "traces", "traces" ],
    "diet_flags" : [ {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    }, {
      "ingredient" : "ingredient",
      "is_allergen" : true,
      "ingredient_description" : "ingredient_description",
      "compatibility_level" : 9,
      "is_compatible" : "is_compatible",
      "diet_label" : "diet_label",
      "compatibility_description" : "compatibility_description"
    } ],
    "countries" : [ "countries", "countries" ],
    "footnote" : "footnote",
    "allergens" : [ "allergens", "allergens" ],
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "ingredient_list" : [ "ingredient_list", "ingredient_list" ],
    "vitamins" : [ "vitamins", "vitamins" ],
    "name" : "name",
    "brand_list" : [ "brand_list", "brand_list" ]
  } ]
}}]
     - parameter allergen: (query) Filter the search to only include branded foods that contain a specific allergen.  __Example__: &amp;allergen&#x3D;Peanuts  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter brand: (query) Filter the search to only include branded foods that are owned by a specific brand.  __Example__: &amp;brand&#x3D;Starbucks  (optional)
     - parameter category: (query) Filter the search to only include branded foods from a specific category.  __Example__: &amp;category&#x3D;Plant Based Foods  (optional)
     - parameter country: (query) Filter the search to only include branded foods that are sold in a specific country.  __Example__: &amp;country&#x3D;United States  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter diet: (query) Filter the search to only include branded foods that are considered compatible with a specific diet.  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter ingredient: (query) Filter the search to only include branded foods that contain a specific ingredient.  __Example__: &amp;ingredient&#x3D;Salt  (optional)
     - parameter keyword: (query) Filter the search to only include branded foods that are associated with a specific keyword.  __Example__: &amp;keyword&#x3D;Organic  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter mineral: (query) Filter the search to only include branded foods that contain a specific mineral.  __Example__: &amp;mineral&#x3D;Potassium  (optional)
     - parameter nutrient: (query) Filter the search to only include branded foods that contain a specific nutrient.  __Example__: &amp;nutrient&#x3D;Caffeine  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter palmOil: (query) Filter the search to only include branded foods that contain a specific ingredient made using palm oil.  __Example__: &amp;palm_oil&#x3D;E160a Beta Carotene  (optional)
     - parameter trace: (query) Filter the search to only include branded foods that contain a specific trace ingredient.  __Example__: &amp;trace&#x3D;Tree Nuts  ___Important Note:__ This parameter cannot be used alone. It must be paired with at least 1 additional parameter._  (optional)
     - parameter vitamin: (query) Filter the search to only include branded foods that contain a specific vitamin.  __Example__: &amp;vitamin&#x3D;Biotin  (optional)
     - parameter limit: (query) Set maximum number of records you want the API to return.  __Example:__ &amp;limit&#x3D;10  (optional)
     - parameter page: (query) This is how you paginate the search result. By default, you will see the first 10 records. You must increment the page number to access the next 10 records, and so on.  __Example__: &amp;page&#x3D;1  (optional)
     - returns: RequestBuilder<BrandedFoodObject> 
     */
    open class func foodBrandedSearchPhpGetWithRequestBuilder(allergen: String? = nil, brand: String? = nil, category: String? = nil, country: String? = nil, diet: Diet_foodBrandedSearchPhpGet? = nil, ingredient: String? = nil, keyword: String? = nil, mineral: String? = nil, nutrient: String? = nil, palmOil: String? = nil, trace: String? = nil, vitamin: String? = nil, limit: Limit_foodBrandedSearchPhpGet? = nil, page: Int32? = nil) -> RequestBuilder<BrandedFoodObject> {
        let path = "/food/branded/search.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
                        "allergen": allergen,
                        "brand": brand,
                        "category": category,
                        "country": country,
                        "diet": diet?.rawValue,
                        "ingredient": ingredient,
                        "keyword": keyword,
                        "mineral": mineral,
                        "nutrient": nutrient,
                        "palm_oil": palmOil,
                        "trace": trace,
                        "vitamin": vitamin,
                        "limit": limit?.rawValue,
                        "page": page?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<BrandedFoodObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     * enum for parameter limit
     */
    public enum Limit_foodIngredientSearchPhpGet: Int32 { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
    }

    /**
     Get raw/generic food ingredient item(s)
     - parameter find: (query) Search our database for a single ingredient or a specific set of ingredients.  __Example #1:__ &amp;find&#x3D;broccoli  __Example #2:__ &amp;find&#x3D;broccoli,cauliflower,spinach&amp;list&#x3D;true  __Important List Notes:__    - Set the \&quot;list\&quot; parameter to \&quot;true\&quot; before passing in a comma-separated list of ingredients.   - Comma-separated lists cannot contain more than __15 ingredients__. You must perform additional API calls if you are looking up more than 15 ingredients.  
     - parameter list: (query) Setting _&amp;list&#x3D;true_ will configure this endpoint to allow searching for ingredients using a comma-separated list. By default, this endpoint will __only__ return results for the first ingredient.  __Example:__ &amp;list&#x3D;true  
     - parameter raw: (query) Optionally filter the search result to only include raw ingredients.  __Example:__ &amp;raw&#x3D;true  (optional)
     - parameter limit: (query) Set maximum number of records you want the API to return, per search term.  __Example:__ &amp;limit&#x3D;3  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func foodIngredientSearchPhpGet(find: Int32, list: Bool, raw: Bool? = nil, limit: Limit_foodIngredientSearchPhpGet? = nil, completion: @escaping ((_ data: IngredientObject?, _ error: ErrorResponse?) -> Void)) {
        foodIngredientSearchPhpGetWithRequestBuilder(find: find, list: list, raw: raw, limit: limit).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get raw/generic food ingredient item(s)
     - GET /food/ingredient/search.php
     - # Get data for a specific ingredient or a specific set of ingredients.  This API endpoint is only available to Standard and Premium API subscribers. Please consider upgrading your subscription if you are subscribed to the Limited plan. _[Read this](https://desk.zoho.com/portal/chompthis/kb/articles/can-i-upgrade-downgrade-my-subscription) if you aren't sure how to upgrade your subscription._  __Example:__ ```https://chompthis.com/api/v2/ingredient/search.php?api_key=API_KEY&find=STRING/LIST&list=BOOLEAN&raw=BOOLEAN``` 
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "items" : [ {
    "protein_conversion_factor" : 0.8008281904610115,
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "name" : "name",
    "description" : "description",
    "categories" : [ "categories", "categories" ],
    "footnote" : "footnote",
    "common_name" : "common_name",
    "nutrients" : {
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ]
  }, {
    "protein_conversion_factor" : 0.8008281904610115,
    "calorie_conversion_factor" : {
      "carbohydrate_value" : 7.457744773683766,
      "protein_value" : 1.4894159098541704,
      "fat_value" : 6.84685269835264
    },
    "components" : [ {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    }, {
      "data_points" : 6,
      "pct_weight" : 6.438423552598547,
      "gram_weight" : 3.5571952270680973,
      "name" : "name",
      "is_refuse" : true
    } ],
    "diet_labels" : {
      "vegetarian" : {
        "confidence_description" : "confidence_description",
        "confidence" : 9,
        "name" : "name",
        "compatibility_level" : 9,
        "is_compatible" : true
      },
      "vegan" : {
        "confidence_description" : "confidence_description",
        "confidence" : 5,
        "name" : "name",
        "compatibility_level" : 4,
        "is_compatible" : true
      },
      "gluten_free" : {
        "confidence_description" : "confidence_description",
        "confidence" : 8,
        "name" : "name",
        "compatibility_level" : 6,
        "is_compatible" : true
      }
    },
    "name" : "name",
    "description" : "description",
    "categories" : [ "categories", "categories" ],
    "footnote" : "footnote",
    "common_name" : "common_name",
    "nutrients" : {
      "usda" : [ {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      }, {
        "data_points" : 1,
        "min" : 2.027123023002322,
        "median" : 7.386281948385884,
        "max" : 4.145608029883936,
        "name" : "name",
        "measurement_unit" : "measurement_unit",
        "rank" : 1,
        "description" : "description",
        "id" : 9,
        "per_100g" : 3.616076749251911,
        "footnote" : "footnote"
      } ]
    },
    "portions" : [ {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    }, {
      "data_points" : 2,
      "modifier" : "modifier",
      "gram_weight" : 1.284659006116532,
      "measurement_unit" : "measurement_unit",
      "description" : "description",
      "footnote" : "footnote"
    } ]
  } ]
}}]
     - parameter find: (query) Search our database for a single ingredient or a specific set of ingredients.  __Example #1:__ &amp;find&#x3D;broccoli  __Example #2:__ &amp;find&#x3D;broccoli,cauliflower,spinach&amp;list&#x3D;true  __Important List Notes:__    - Set the \&quot;list\&quot; parameter to \&quot;true\&quot; before passing in a comma-separated list of ingredients.   - Comma-separated lists cannot contain more than __15 ingredients__. You must perform additional API calls if you are looking up more than 15 ingredients.  
     - parameter list: (query) Setting _&amp;list&#x3D;true_ will configure this endpoint to allow searching for ingredients using a comma-separated list. By default, this endpoint will __only__ return results for the first ingredient.  __Example:__ &amp;list&#x3D;true  
     - parameter raw: (query) Optionally filter the search result to only include raw ingredients.  __Example:__ &amp;raw&#x3D;true  (optional)
     - parameter limit: (query) Set maximum number of records you want the API to return, per search term.  __Example:__ &amp;limit&#x3D;3  (optional)
     - returns: RequestBuilder<IngredientObject> 
     */
    open class func foodIngredientSearchPhpGetWithRequestBuilder(find: Int32, list: Bool, raw: Bool? = nil, limit: Limit_foodIngredientSearchPhpGet? = nil) -> RequestBuilder<IngredientObject> {
        let path = "/food/ingredient/search.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
                        "find": find.encodeToJSON(),
                        "list": list,
                        "raw": raw,
                        "limit": limit?.rawValue
        ])

        let requestBuilder: RequestBuilder<IngredientObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
